stashed/nats

Dockerfile.dbg, Dockerfile.in
=> [cherry-pick] Prepare docker image for multi arch

go.mod, go.sum, vendor/go.bytebuilders.dev/license-verifier/Makefile, vendor/go.bytebuilders.dev/license-verifier/info/lib.go, vendor/go.bytebuilders.dev/license-verifier/kubernetes/go.mod, vendor/go.bytebuilders.dev/license-verifier/kubernetes/lib.go, vendor/go.bytebuilders.dev/license-verifier/lib.go, vendor/modules.txt
=> [cherry-pick] Update dependencies (#15)

go.mod, go.sum, vendor/go.bytebuilders.dev/license-verifier/info/lib.go, vendor/go.bytebuilders.dev/license-verifier/kubernetes/go.mod, vendor/go.bytebuilders.dev/license-verifier/kubernetes/lib.go, vendor/go.bytebuilders.dev/license-verifier/lib.go, vendor/modules.txt
=> [cherry-pick] Fix SiteInfo publishing (#17)

pkg/backup.go, pkg/root.go, pkg/util.go
=> [cherry-pick] make fmt (#30)

.github/workflows/ci.yml, Makefile
=> [cherry-pick] Use Go 1.18 (#32)

Makefile, go.mod, go.sum, vendor/kmodules.xyz/client-go/api/v1/timeofday.go, vendor/kmodules.xyz/client-go/meta/incluster.go, vendor/modules.txt
=> [cherry-pick] Use restic 0.13.1 (#40)

Dockerfile.dbg, Dockerfile.in, Makefile, pkg/backup.go, pkg/restore.go
Signed-off-by: hmsayem <hmsayem@appscode.com>
=> Add Account Backup

go.mod, go.sum, vendor/modules.txt
=> Prepare for release v2022.05.18

pkg/backup.go, pkg/restore.go, pkg/util.go
Signed-off-by: piyush1146115 <piyush@appscode.com>
=> Make sure to fail the backup/restore sessions if license check fails.

pkg/backup.go, pkg/restore.go, pkg/util.go
* Make sure to fail the backup/restore sessions if license check fails.
Signed-off-by: piyush1146115 <piyush@appscode.com>
* Refactor implementation.
Signed-off-by: piyush1146115 <piyush@appscode.com>
=> [cherry-pick] Make sure to fail the backup/restore sessions if license check fails. (#52)

Makefile
=> [cherry-pick] Use restic 0.14.0 (#66)

Makefile
=> [cherry-pick] Revert to restic 0.13.1 (#69)

.github/workflows/cherry-pick.yml, .github/workflows/ci.yml, .github/workflows/release-tracker.yml, .github/workflows/release.yml
=> [cherry-pick] Run GH actions on ubuntu-20.04 (#75)

go.mod, go.sum, vendor/modules.txt, vendor/stash.appscode.dev/apimachinery/apis/constants.go, vendor/stash.appscode.dev/apimachinery/pkg/restic/config.go
Release: v2023.01.05
Release-tracker: https://github.com/stashed/CHANGELOG/pull/60
=> Prepare for release 2.8.2-v4

.github/workflows/ci.yml, Makefile, go.mod, go.sum, vendor/golang.org/x/crypto/AUTHORS, vendor/golang.org/x/crypto/CONTRIBUTORS, vendor/golang.org/x/crypto/pkcs12/crypto.go, vendor/golang.org/x/crypto/pkcs12/internal/rc2/rc2.go, vendor/modules.txt
=> [cherry-pick] Update workflows (Go 1.20, k8s 1.26) (#87)

go.mod, go.sum, vendor/modules.txt, vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go
Release: v2023.03.13
Release-tracker: https://github.com/stashed/CHANGELOG/pull/63
=> Prepare for release 2.6.1-v11

go.mod, go.sum, vendor/modules.txt, vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go
Release: v2023.03.13
Release-tracker: https://github.com/stashed/CHANGELOG/pull/63
=> Prepare for release 2.8.2-v6

Dockerfile.dbg, Dockerfile.in
=> Use numeric uid in Dockerfile

Dockerfile.dbg, Dockerfile.in
=> [cherry-pick] Use numeric uid in Dockerfile (#97)

go.mod, go.sum, vendor/modules.txt, vendor/stash.appscode.dev/apimachinery/apis/repositories/v1alpha1/openapi_generated.go, vendor/stash.appscode.dev/apimachinery/apis/stash/v1alpha1/openapi_generated.go, vendor/stash.appscode.dev/apimachinery/apis/stash/v1beta1/openapi_generated.go, vendor/stash.appscode.dev/apimachinery/apis/ui/v1alpha1/openapi_generated.go, vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go, vendor/stash.appscode.dev/apimachinery/pkg/restic/restore.go
Release: v2023.04.30
Release-tracker: https://github.com/stashed/CHANGELOG/pull/65
=> Prepare for release 2.6.1-v13

go.mod, go.sum, vendor/modules.txt, vendor/stash.appscode.dev/apimachinery/apis/repositories/v1alpha1/openapi_generated.go, vendor/stash.appscode.dev/apimachinery/apis/stash/v1alpha1/openapi_generated.go, vendor/stash.appscode.dev/apimachinery/apis/stash/v1beta1/openapi_generated.go, vendor/stash.appscode.dev/apimachinery/apis/ui/v1alpha1/openapi_generated.go, vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go, vendor/stash.appscode.dev/apimachinery/pkg/restic/restore.go
Release: v2023.04.30
Release-tracker: https://github.com/stashed/CHANGELOG/pull/65
=> Prepare for release 2.8.2-v8

pkg/backup.go
Signed-off-by: hmsayem <hmsayem@appscode.com>
=> [cherry-pick] Fix Cleanup log (#96)

go.mod, go.sum, vendor/modules.txt, vendor/stash.appscode.dev/apimachinery/apis/repositories/v1alpha1/openapi_generated.go, vendor/stash.appscode.dev/apimachinery/apis/stash/v1alpha1/openapi_generated.go, vendor/stash.appscode.dev/apimachinery/apis/stash/v1beta1/openapi_generated.go, vendor/stash.appscode.dev/apimachinery/apis/ui/v1alpha1/openapi_generated.go
Release: v2024.4.8
Release-tracker: https://github.com/stashed/CHANGELOG/pull/72
=> Prepare for release 2.8.2-v14

.github/workflows/cherry-pick.yml, .github/workflows/ci.yml, .github/workflows/release-tracker.yml, .github/workflows/release.yml, Makefile
=> Use Go 1.23 (#144)

Makefile
=> [cherry-pick] Use debian:12 base image (#154)

Dockerfile.dbg, Dockerfile.in
=> [cherry-pick] Use debian:12 base image (#157)

Makefile, go.mod, go.sum, vendor/modules.txt, vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go, vendor/stash.appscode.dev/apimachinery/pkg/restic/config.go, vendor/stash.appscode.dev/apimachinery/pkg/restic/migrate.go
Signed-off-by: Md. Ishtiaq Islam <ishtiaq@appscode.com>
=> [cherry-pick] Update restic version (#168)

.github/workflows/ci.yml, .github/workflows/release.yml
=> [cherry-pick] Disable image caching in setup-qemu action (#171)

.github/workflows/ci.yml, Makefile
=> [cherry-pick] Use Go 1.24 (#177)

go.mod, go.sum, pkg/backup.go, vendor/modules.txt, vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go, vendor/stash.appscode.dev/apimachinery/pkg/restic/output.go, vendor/stash.appscode.dev/apimachinery/pkg/restic/unlock.go
Signed-off-by: Anisur Rahman <anisur@appscode.com>
=> [cherry-pick] Add Automatic Restic Unlock feature (#183)

.github/workflows/ci.yml, Makefile
=> [cherry-pick] Use Go 1.25 (#189)
